services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - anime-mcp-network
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  fastapi:
    build: .
    container_name: anime-mcp-server
    ports:
      - "8000:8000"  # FastAPI REST API
      - "8001:8001"  # MCP Server HTTP
    networks:
      - anime-mcp-network
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=anime_database
      - ENABLE_MULTI_VECTOR=true
      - SERVER_MODE=stdio  # Change to 'http' for HTTP mode
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
    volumes:
      - ./data:/app/data

  mcp-server:
    build: .
    container_name: anime-mcp-http-server
    ports:
      - "8001:8001"  # MCP Server HTTP
    networks:
      - anime-mcp-network
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=anime_database
      - ENABLE_MULTI_VECTOR=true
      - SERVER_MODE=http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "src.mcp.server", "--mode", "http", "--host", "0.0.0.0", "--port", "8001"]

networks:
  anime-mcp-network:
    driver: bridge
