services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - anime-mcp-network
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  fastapi:
    build: .
    container_name: anime-mcp-server
    ports:
      - "8000:8000"
    networks:
      - anime-mcp-network
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=anime_database
    volumes:
      - ./data:/app/data

networks:
  anime-mcp-network:
    driver: bridge
